urls.py
from django.views.generic.simple import direct_to_template
from django.conf.urls.defaults import *
from django.conf import settings
from django.views.generic import TemplateView

from userena import views as userena_views
from callforme import forms as callforme_forms
from callforme import views as callforme_views

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

message = """
This is a test.
"""

urlpatterns = patterns('',
    # Examples:
    # 
        
    #url(r'^$', 'callforme.views.home', name='home'),
    url(r'^$', direct_to_template,
        {'template': 'index.html'}, name='home'),  

    url(r'^contacts/new/$', 'callforme.views.add_contact', name="add-contact"),
    url(r'^contacts/(?P<contact_id>\d+)/$', 'callforme.views.contact_detail', name="contact-detail"),
    url(r'^contacts/$', 'callforme.views.contacts', name='contacts'),
    url(r'^contacts/(?P<contact_id>\d+)/delete/$', 'callforme.views.contact_delete', name='contact-delete'),

 #   url(r'^promo/$',
 #       direct_to_template,
 #       {'template': 'promo.html'},
 #       name='promo'),
    # url(r'^hubbing/', include('hubbing.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', include(admin.site.urls)),

#    url(r'^$', 'django_twilio.views.say', {'text': message}),


#Deactivating next block til site is finished
    url(r'^testsms/$', 'callforme.views.testsms'),
    url(r'^sms/$', 'callforme.views.twilio_sms'),
    url(r'^call/$', 'callforme.views.twilio_call', name="call"),
    url(r'^verify\-phone/$', 'callforme.views.twilio_verify'),
    url(r'^twiml\-response/$', 'callforme.views.twiml_response'),
    url(r'^twiml\-connect/$', 'callforme.views.twiml_connect'),
    # from https://github.com/bread-and-pepper/django-userena/issues/83#issuecomment-1733415
    url(r'^accounts/signup/$', 
        userena_views.signup, 
        {'signup_form': callforme_forms.SignupFormCustomized}),     
    # account stuff using userena
    url(r'^accounts/', include('userena.urls')),
    url(r'^messages/', include('userena.contrib.umessages.urls')),

    url(r'^i18n/', include('django.conf.urls.i18n')),   
    url(r'^about/', direct_to_template,
        {'template': 'about.html'}),
    url(r'^contact/', direct_to_template,
        {'template': 'contact.html'}),    
    # url(r'^$', 'django_twilio.views.conference', {
    #     'name': 'conf1',
    #     'wait_url': 'http://twimlets.com/holdmusic?Bucket=com.twilio.music.rock',
    #     'wait_method': 'GET',
    # }),
)

if settings.DEBUG:
    urlpatterns += patterns('',
                            url(r'^site_media/(?P<path>.*)$',
                                'django.views.static.serve',
                                {'document_root': 'static'}))
                                

callforme/models.py
from django.db import models
from django.contrib.auth.models import User
from django.forms import ModelForm
from django.forms.extras.widgets import SelectDateWidget

class Contact(models.Model):
    user = models.ForeignKey(User)
    name = models.CharField(max_length = 200)
    phone = models.CharField(max_length = 200)
    birthday = models.DateField(blank=True, null=True)
    twitter = models.CharField(max_length=255, blank=True, null=True)
    
    FREQUENCY_CHOICES = (
        ('W', 'Weekly'),
        ('B', 'Bi-weekly'),
        ('M', 'Monthly'),
        )
    frequency = models.CharField(max_length=1, choices=FREQUENCY_CHOICES)

class ContactForm(ModelForm):
    class Meta:
        model = Contact
        exclude = ('user',)
        
class Call(models.Model):
    user = models.ForeignKey(User)
    contact = models.ForeignKey(Contact)
    time = models.DateTimeField(auto_now_add = True)
   

profiles/models.py
from django.db import models
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth.models import User

from userena.models import UserenaLanguageBaseProfile

import datetime

class Profile(UserenaLanguageBaseProfile):
    """ Default profile """

    user = models.OneToOneField(User,
                                unique=True,
                                verbose_name=_('user'),
                                related_name='profile') 

    name =  models.CharField(max_length=255, blank=True)
    phone = models.CharField(_('Phone Number'), max_length=255, blank=True, null=True)

templates/_account_bar.html
{% load i18n %}
<ul class="secondary-nav">
    <li>
    {% if user.is_authenticated %}
        <a href="#" class="menu">{{ user }}</a>
        <ul class="menu-dropdown">
            {% if user.is_staff %}
                <li><a href="/admin/">Admin</a></li>
                <li><a href="{% url userena_profile_list %}"><span>{% trans 'All profiles' %}</span></a></li>
                <li><a href="{% url userena_umessages_list %}"><span>{% trans 'Messages' %}</span></a></li>
            {% endif %}            
            
            <li><a href="{% url userena_profile_detail user.username %}"><span>{% trans 'Account' %} ({{ user.username }})</span></a></li>
            <li class="divider"></li>
            <li><a href="{% url userena_signout %}"><span>{% trans 'Signout' %}</span></a></li>
        </ul>
    {% else %}
    <li><a href="{% url userena_signin %}"><span>{% trans 'Log in' %}</span></a></li>
    <li><a href="{% url userena_signup %}"><span>{% trans 'Sign up' %}</span></a></li>
    {% endif %}
</ul>

templates/_footer.html
<footer>
  <p>&copy; PickupConnect 2011</p>
</footer>

templates/_googleanalytics.html
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-26539222-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>

templates/about.html
{% extends "main_site_base.html" %}

{% block head_title %}About{% endblock %}
{% block body_title %}About{% endblock %}
{% block body_text %}<p>pickup<b>connect</b> is phone service that wants to help you stay in touch with those you care about.  Use it to schedule weekly, bi-weekly or monthly phone calls.</p>
<p>pickup<b>connect</b> was formed at Start-up Weekend Boston October, 2011 by <a href="http://noderabbit.com/">Nate Aune</a>, <a href="http://nteddywing.com/"</a>Teddy Wing</a>, <a href="
<a href="http://www.linkedin.com/profile/view?id=65195525">John Coogan</a>, SuiLin Yap, Nick Pigott and <a href="http://SteveHershman.com/">Steve Hershman</a>.{% endblock %}

templates/add_contact.html
{% extends "site_base.html" %}

{% load i18n %}
{% load bootstrap_tags %}

{% block head_title %}
Add contact
{% endblock %}

{% block body %}
<div class="page-header">
    <h1>Add contact</h1>
</div>
<div class="well">
<form action="" method="post">
  {% csrf_token %}
  <fieldset class="inlineLabels">
      {{ form|as_bootstrap }}
  </fieldset>
  <div class="actions">
      <input class="btn primary large" type="submit" value="{% trans "Add contact" %}" />
  </div>
</form>
</div>
{% endblock %}
{% block extra_body %}
    <script type="text/javascript">
        $(function(){
            $("#id_name").focus();
        });
    </script>
{% endblock %}

templates/bootstrap_base.html
<!DOCTYPE html>
<html lang="{{ LANGUAGE_CODE }}">
    <head>
        <meta charset="utf-8" />
        <title>{% block head_title_base %}{% if SITE_NAME %}{{ SITE_NAME }} : {% endif %}{% block head_title %}{% endblock %}{% endblock %}</title>
        <!-- HTML5 shim, for IE6-8 support of HTML elements -->
        <!--[if lt IE 9]>
            <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
        <![endif]-->
        <!-- <link rel="shortcut icon" href="{{ STATIC_URL }}img/favicon.png" /> -->
        <link rel="stylesheet" href="{{ STATIC_URL }}css/bootstrap.css">
        <link rel="stylesheet" href="{{ STATIC_URL }}css/extra.css">
        <script src="{{ STATIC_URL }}js/jquery-1.6.4.min.js"></script>
        <script src="{{ STATIC_URL }}js/jquery.form.js"></script>
        <script src="{{ STATIC_URL }}js/bootstrap-alerts.js"></script>
        <script src="{{ STATIC_URL }}js/bootstrap-twipsy.js"></script>
        <script src="{{ STATIC_URL }}js/bootstrap-popover.js"></script>
        <script src="{{ STATIC_URL }}js/bootstrap-dropdown.js"></script>
        <script src="{{ STATIC_URL }}js/theme.js"></script>
        <!--<script src="{{ STATIC_URL }}js/pinax.modal.js"></script> -->
        {% block extra_head_base %}
            {% block extra_head %}{% endblock %}
        {% endblock %}
    </head>
    <body class="{% block body_class %}{% endblock %}" id="{% block body_id %}{% endblock %}">
        
        {% block topbar_base %}
        <div class="topbar-wrapper" style="z-index: 5;">
          <div class="topbar">
            <div class="topbar-inner">
              <div class="container">
                  {% block topbar %}
                  <h3><a href="{% url home %}">pickup<strong>connect</strong></a></h3>
                        {% block nav %}{% endblock %}
                        {% block account_bar %}{% include "_account_bar.html" %}{% endblock %}
                  {% endblock %}
              </div>
            </div>
          </div>
        </div>
        {% endblock %}
        
        {% block body_base %}
            <div class="container">
                {% if messages %}
                {% for message in messages %}
                <div class="alert-message{% if message.tags %} {{ message.tags }}{% endif %}">
                 <a class="close" href="#">&times;</a><p>{{ message }}</p>
                </div>
                {% endfor %}
                {% endif %}
                {% block body %}
                {% endblock %}
            </div>
        {% endblock %}
        
        {% block footer_base %}
            <div id="footer">
                <div class="inner">
                    <div class="container">
                        {% block footer %}{% endblock %}
                    </div>
                </div>
            </div>
        {% endblock %}
        
        {% block extra_body_base %}
            {% block extra_body %}{% endblock %}
        {% endblock %}
    </body>
</html>

templates/call.html
{% extends "site_base.html" %}

{% block head_title %}Calling...{% endblock %}

{% block body %}
<div class="container">

  <!-- Main hero unit for a primary marketing message or call to action -->
  <div class="row">
    <div class = "span4">
     <h1></h1>
    </div>
    <div class="span12">
      <h1 style="font-weight: bold; font-size: 105px;">Calling&hellip;</h1>
    </div>

</div> <!-- /container -->
{% endblock %}

templates/contact.html
{% extends "main_site_base.html" %}

{% block head_title %}Contact{% endblock %}
{% block body_title %}Contact{% endblock %}
{% block body_text %}We'd love to hear from you.  Find us on <a href="https://twitter.com/#!/PickupConnect">Twitter</a> or <a href="mailto:PickupConnect@SteveHershman.com?Subject=Hello">email us</a>.{% endblock %}

templates/contact_detail.html
{% extends "site_base.html" %}

{% load famfam_icon %}
{% load i18n %}
{% load bootstrap_tags %}

{% block head_title %}
{{ contact.name }}
{% endblock %}

{% block body %}
<div class="page-header">
    <a href="{% url add-contact %}"><div style="float:right;">{% famfam_silk 'user_add' %} Add a new contact</div></a>
    <h1>{{ contact.name }}</h1>
</div>
<div class="well">
<form action="" method="post">
  {% csrf_token %}
  <fieldset class="inlineLabels">
      {{ form|as_bootstrap }}
  </fieldset>
  <div class="actions">
      <input class="btn primary large" type="submit" value="{% trans "Save" %}" />
  </div>
</form>
</div>
{% endblock %}
{% block extra_body %}
    <script type="text/javascript">
        $(function(){
            $("#id_name").focus();
        });
    </script>
{% endblock %}

templates/contacts.html
{% extends "site_base.html" %}

{% load famfam_icon %}

{% block head_title %}
My contacts
{% endblock %}

{% block body %}
<div class="page-header">
    <a href="{% url add-contact %}"><div style="float:right;">{% famfam_silk 'user_add' %} Add a new contact</div></a>
    <h1>My contacts</h1>
</div>
<div class="container">

    <div class="row">
        <div class="span10">
          {% if contact_list %}
          <table class="zebra-striped" id="projectsTable">
            <thead>
                <tr>
                    <th>Contact</th>
                    <th>Phone number</th>
                    <th>Twitter</th>
                    <th>Birthday</th>
                    <th>Frequency</th>
                    <th>Delete?</th>
                </tr>
            </thead>
            <tbody>
            {% for c in contact_list %}
            <tr>
                <td><a href="./{{ c.id }}/">{% famfam_silk 'user' %} {{c.name}}</a></td>
                <td>{{ c.phone }}</td>
                <td>{{ c.twitter }}</td>
                <td>{{ c.birthday }}</td>
                <td>{{ c.get_frequency_display }}</td>
                <td><a id="delete-{{ c.id }}" class="delete-contact" href="./{{ c.id }}/delete/">Delete</a></td>
            </tr>
            {% endfor %}
            </tbody>
          </table>
          <a href="{% url call %}" class="btn success large">Start connecting me!</a>
          <a href="#" class="btn danger large">Stop the calls</a>
          {% else %}
            <p>You have no contacts yet.</p>
            <p>Why don't you start adding some?</p>
            <a href="{% url add-contact %}" class="btn success large">Add a contact</a>
          {% endif %}
        </div>
        
    </div>
</div>
{% endblock %}
{% block extra_body %}
<script src="{{ STATIC_URL }}js/jquery.tablesorter.min.js"></script>
<script >
  $(function() {
    $("table#projectsTable").tablesorter({ sortList: [[0,0]] });
    
    $('.delete-contact').click(function() {
        if (confirm('Are you sure you want to delete "' + $(this).parent().parent().children(':first').children().text().substr(1) + '" from your list of contacts?')) {
            window.location.href = './' + $(this).attr('id').replace('delete-', '') + '/delete';
        }
    }).attr('href', '#');
  });
</script>
{% endblock %}

templates/form.html
{% if form.non_field_errors %}
    <div>
        {% if form_error_title %}<h3>{{ form_error_title }}</h3>{% endif %}
        <ol>
            {{ form.non_field_errors|unordered_list }}
        </ol>
    </div>
{% endif %}
{% for field in form %}
    {% if field.is_hidden %}
        {{ field }}
    {% else %}
        <div class="clearfix{% if field.errors %} error{% endif %}">
            {% if field.label %}
                <label for="{{ field.auto_id }}" {% if field.field.required %}class="requiredField"{% endif %}>
                    {{ field.label|safe }}
                </label>
                <div class="input">
                    {{ field }}
                    {% for error in field.errors %}
                        <span class="help-block-inline">{{ error|safe }}</span>
                    {% endfor %}
                    {% if field.help_text %}
                        <span class="help-inline">{{ field.help_text|safe }}</span>
                    {% endif %}
                </div>
            {% endif %}
        </div>
    {% endif %}
{% endfor %}

templates/index.html
{% extends "site_base.html" %}

{% load famfam_icon %}

{% block head_title %}Home{% endblock %}

{% block body %}
<div class="container">

  <!-- Main hero unit for a primary marketing message or call to action -->
  {% if not user.is_authenticated %}

<div class="hero-unit">
<div class="container">
    <div class="row">
        <div class="span6">
                <h1>
                    Stay in touch!
                </h1>
                <p>
                    We want to help you you stay in touch with your friends and loved ones.
                    
                <ul style="list-style-image: url({{ STATIC_URL }}img/icons/accept.png);">
                    <li>Register, teach us about your contacts.</li>
                    <li>We'll call you with gentle reminders about all those phone calls you've been procrastinating.</li>
                    <li>With your permission, we'll even automatically bring your buddy on the line.</li>
                </ul>
                </p>
                <a href="{% url userena_signup %}" class="btn success large">Sign up now!</a>
        </div>
        <div class="span10">
            <iframe scrolling="no" allowTransparency="true" frameborder="0" width="400" height="258" src="http://goanimate.com/player/embed/0tn9mxN-g_ug"></iframe>
            <p>Press play to watch this 1 minute video.</p>
        </div>
    </div>
</div>
</div>

  {% else %}
  <div class="row">
    <div class = "span4">
     <h1>Welcome!</h1>
    </div>
    <div class="span12">
      <p>Why don't you add some <a href="/contacts">contacts</a>?</p>
{% if DEBUG %}
      <span class="label important">Maybe add future call schedule here</span>
{% endif %}
    </div>
  {% endif %}

  <!-- Example row of columns -->
<div class="row">
    <div class="span-one-third">
      <h2>1. Add friends/family</h2>
      <p>Tell PickupConnect who your friends are, what their phone numbers are, and how often you'd like to talk with them. </p>
    </div>
    <div class="span-one-third">
      <h2>2. Commence calling</h2>
       <p>Once you're ready, start the PickupConnect bot and it will start calling you on a regular basis to connect you with your friends.</p>
   </div>
    <div class="span-one-third">
      <h2>3. Stay connected!</h2>
      <p>When you receive a phone call from PickupConnect, it will announce which friend it is trying to connect you with.</p><p>You simply press 1# to continue to be connected, and then you're talking with your friend. It's that easy!</p>
    </div>
  </div>

</div> <!-- /container -->
{% endblock %}

templates/main_site_base.html
{% extends "site_base.html" %}

{% block head_title %}{% endblock %}



{% block body %}
<div class="container">
<div class="row">
<div class="span4"><h1>{% block body_title %}{% endblock %}</h1></div>
<div class="span12">{% block body_text %}{% endblock %}</div>
</div> <!-- /row -->
</div> <!-- /container -->

{% endblock %}

templates/site_base.html
{% extends "bootstrap_base.html" %}

{% block head_title %}{% endblock %}

{% block extra_head_base %}
    {% include '_googleanalytics.html' %}
{% endblock %}

{% block nav %}
<ul class="nav">
	{% if user.is_authenticated %}
        <li {% ifequal section "contacts" %} class="active" {% endifequal %}>
            <a href="/contacts">Contacts</a>
        </li>
        <li {% ifequal section "settings" %} class="active" {% endifequal %}>
            <a href="/settings">Settings</a>
        </li>
        {% endif %}


        <li {% ifequal section "about" %} class="active" {% endifequal %}>
            <a href="/about">About</a>
        </li>
        <li {% ifequal section "contact" %} class="active" {% endifequal %}>
            <a href="/contact">Contact</a>
        </li>
</ul>
{% endblock %}

{% block body %}
{% endblock %}

{% block footer %}
    {% include '_footer.html' %}
{% endblock %}